apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: bW9uZ28tZGItcGFzcw==
  # Example:
  # password: {{ .Values.password | b64enc }}